### ISSUE TITLE
cannot install deps

### ISSUE THREAD

**Issue by quangv** [rphlmr/supa-remix-stack#1]
Hi thanks for these remix stacks.

There's an error with `npx create-remix@latest --template rphlmr/supa-remix-stack` regarding dependencies.

```
npm install
npm WARN ERESOLVE overriding peer dependency
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @remix-run/dev@2.0.1
npm ERR! Found: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^5.1.0" from @remix-run/server-runtime@2.0.1
npm ERR!   node_modules/@remix-run/dev/node_modules/@remix-run/server-runtime
npm ERR!     @remix-run/server-runtime@"2.0.1" from @remix-run/dev@2.0.1
npm ERR!     node_modules/@remix-run/dev
npm ERR!       dev @remix-run/dev@"^2.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^5.1.0" from @remix-run/dev@2.0.1
npm ERR! node_modules/@remix-run/dev
npm ERR!   dev @remix-run/dev@"^2.0.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@5.2.2
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^5.1.0" from @remix-run/dev@2.0.1
npm ERR!   node_modules/@remix-run/dev
npm ERR!     dev @remix-run/dev@"^2.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

`rphlmr/supa-stripe-stack` & `rphlmr/supa-fly-stack` seems to have similar issues.

I filed a similar bug with [`netlify/remix-template`](https://github.com/netlify/remix-template/issues/125) that they [fixed](https://github.com/netlify/remix-template/pull/124), unsure it's the exact same thing though.

**Comment by rphlmr** [comment]
Hello,

Sorry for that, I don't use this stack that much 😅.

I have updated it to Remix v2, It should works (not tested to deploy on Vercel).

**Comment by quangv** [comment]
Thanks @rphlmr for quickly addressing this. (It was way more code than I suspected).

Fyi, when I do the `npx create-remix@latest --template rphlmr/supa-remix-stack`, I get error:

```
      ▲  Oh no! Template's remix.init script failed
```

**Comment by rphlmr** [comment]
Will look at that, I remember reading something about that.

You can still clone the repo and change the app name in the package.json if you can’t wait.
It’s basically the same thing.
